import type { Metadata } from "next";
import "./globals.css";
import "@fontsource/noto-sans-kr"; // Defaults to weight 400
import "@fontsource/noto-sans-kr/400.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko-KR">
      <body>
        <header>
          <Link href="/">index</Link>
          &nbsp;
          <Link href="/search">Search</Link>
          &nbsp;
          <Link href="/book/1">book/1</Link>
        </header>
        {children}
      </body>
    </html>
  );
}
