import type { Metadata } from "next";
import "./globals.css";
import "@fontsource/noto-sans-kr"; // Defaults to weight 400
import "@fontsource/noto-sans-kr/400.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
